@extends('layouts.app')

@section('styles')
    <style>
        /* -----------------   */

        .privacy-policy .content-container h2 {
            margin-top: 25px;
            font-size: 22px;
        }

        .privacy-policy .content-container h3 {
            font-size: 16px;
        }

        .privacy-policy .content-container p {
            margin-bottom: 10px;
            text-align: justify;
        }

        .privacy-policy .content-container li {
            list-style: disc;
            font-size: 16px;
            color: #656871;
            margin-bottom: 7px;
            line-height: 1.6;
        }

        @media(max-width:450px) {
            .privacy-policy .content-container h2 {
                font-size: 18px;
            }

            .privacy-policy .content-container h3 {
                font-size: 14px;
            }

            .privacy-policy .content-container p {
                font-size: 14px;
            }

            .privacy-policy .content-container li {
                font-size: 14px;
            }

        }
    </style>
@endsection

@section('content')
    <section class="privacy-policy">
        <div class="content-container">

            <h1>Privacy Policy</h1>

            <p>Conqueror Services LLC. (”Conqueror,” ”Dbyte,” “ukbytes” “we,” “us,” or “our”) are committed to the
                protection of your privacy. This privacy policy ("Policy") outlines the collection, use, sharing, storage,
                transfer, and protection (collectively, "Processing") of your Personal Information. This document delineates
                why and how we process your Personal Information, as detailed in the "About this Policy" section. We
                periodically update this Policy to reflect evolving practices.
            </p>
            <h2>About this Policy</h2>
            <p>This Policy delineates the processing of Personal Information by Conqueror Services LLC, its customers (the
                "Establishments"), in relation to food orders placed through online ordering platforms and associated
                products and services offered by Conqueror Services LLC (the "Services"). Additionally, it outlines how we
                process your Personal Information on behalf of Establishments, such as administering loyalty programs or
                providing email marketing services for sending Messages. If Establishments process your Personal Information
                for other purposes, we encourage you to directly engage with them to address your rights or gain insights
                into their Processing practices.
            </p>

            <p>This Policy also elucidates how we process your Personal Information when you engage with our website, mobile
                application, and other platforms collectively termed as the "Conqueror AI Platforms." This encompasses
                information gathered through Cookies. For further details, please refer to the "How does Conqueror Services
                LLC use Cookies?" section.
            </p>

            <h2>What is personal information? </h2>
            <p>For the context of this Policy, “Personal Information” refers to any data about an identifiable individual,
                encompassing information that alone or combined with other data identifies, contacts, or locates a single
                person. In general, it excludes business contact information, such as name, title, or business contact
                details.
            </p>

            <h2>What personal information do we collect? </h2>
            <p>What personal information do we collect? </p>

            <li>Contact information (e.g., your name, address, email and phone number, username and passwords of your
                account, if any); </li>
            <li>Date of birth;
            </li>
            <li>Social media accounts; </li>
            <li>Technical information (e.g., information about your mobile and/or computer devices, GPS location or the
                unique identifier of your device, the transactions you make).
            </li>


            <h2>How do we collect your personal information? </h2>

            <p>Directly from you Primarily, we gather the necessary Personal Information directly from you, such as when
                utilizing the Service, browsing Conqueror Services LLC Platforms, visiting an Establishment’s website, or
                engaging in communication with us. We may also collect data generated by your mobile/computer devices, like
                mobile advertising identifiers, location information, and IP addresses. Refer to the "How does Conqueror
                Services LLC provide online advertising?" section for more details.
            </p>

            <h2>Legal Basis or Consent </h2>

            <p>Processing your Personal Information typically relies on your consent unless other applicable laws permit
                alternative legal grounds (e.g., compliance with legal obligations, establishment, exercise, or defense of
                legal claims, ongoing or prospective legal proceedings).
            </p>
            <p>Refusal of Collection and Withdrawal of Consent You retain the right to refuse the Processing of your
                Personal Information. Similarly, you can, at any time and subject to reasonable notice and relevant legal or
                contractual restrictions, withdraw your consent (if granted) to the Processing of your Personal Information
                held by us. However, opting not to provide certain Personal Information may impede your ability to utilize
                the Service, as this data is crucial for its provision. Contact Conqueror AI, as detailed in the "How to
                contact us?" section, to address any concerns or queries regarding this matter.
            </p>

            <h2>Why do we collect your personal information?
            </h2>
            <p>For specific and limited Purposes DAILYBITE generally collects your Personal Information to:
            </p>

            <li>Enable you to order products from an Establishment, confirm successful orders, track the closest
                Establishment to your location, and facilitate product delivery if applicable, as part of providing you with
                the Service.
            </li>
            <li>Respond to your queries or questions.</li>
            <li>Authenticate account users.</li>
            <li>Provide advertising while using the Service, Conqueror Services LLC Platforms, Messages, or third-party
                services, including social media.
            </li>
            <li>Offer service and product recommendations based on your preferences.
            </li>
            <li>Administer surveys you've agreed to complete.</li>
            <li>Administer Establishment loyalty programs.
            </li>
            <li>Send Messages and manage email campaigns on behalf of the Establishments (collectively, the “Purposes”).
            </li>

            <h2>Sending Messages </h2>

            <p>If you consent to receive information, Conqueror Services LLC may send newsletters, electronic messages, news
                on new features/products, updates, contests, special offers, and other written communications (“Messages”)
                about Conqueror AI services/products or third-party products/services, including the Establishments.
                Messages may be sent by Conqueror Services LLC or on behalf of the Establishments. Contact the
                Establishments to address your rights or learn more about how they Process your Personal Information.
                Conqueror AI might also use Direct Push and geographical information on the mobile application to send
                alerts about local promotions.
            </p>
            <p>You can opt-out of receiving Messages per the “How to contact us?” section or by following instructions in
                the Messages. You may also disable Direct Push notices via your device settings. A ten-day processing period
                may apply. However, Conqueror AI may continue sending Messages about available upgrades, critical technical
                service issues, or important account information.
            </p>

            <h2>Secondary Purposes </h2>
            <p>Conqueror Services LLC may aggregate and anonymize Personal Information provided to create statistical data
                used to enhance the Service, examine trends, train machine learning algorithms, or share with third-party
                partners, including Establishments, advertising partners, and research centers. Such statistical data
                excludes Personal Information.
            </p>
            <h2>Who do we share your Personal Information with?
            </h2>
            <p>
                Conqueror Services LLC does not rent or sell your Personal Information to third parties and shares it only
                as necessary by law or for specific Purposes.

            </p>
            <h2>With our Employees </h2>
            <p>Employees access your Personal Information solely for work-related purposes, such as when you contact us or
                request support, limiting access to what's necessary for their duties.
            </p>
            <h2>With Strategic Partners
            </h2>
            <p>Conqueror Services LLC may share your Personal Information with partners like Establishments as required for
                the Purposes. Third-party services, including payment processors, delivery companies, hosting services,
                loyalty program providers, and customer support contractors, might access your Personal Information for
                specific business operations.
            </p>
            <h2>When Required by Applicable Laws
            </h2>
            <p>Conqueror Services LLC may share your Personal Information when required by law or in good faith to:
            </p>
            <li>Comply with legal obligations or judicial orders.
            </li>
            <li>Protect and defend Conqueror AI's rights or property.
            </li>
            <li>Verify your compliance with agreements.
            </li>
            <li>Prevent fraud or illegal activity via the Service.</li>
            <li>Safeguard personal safety or public interests.
            </li>

            <h2>During Business Transfer </h2>
            <p>Sharing your Personal Information might occur during business operations such as mergers, acquisitions,
                bankruptcies, or asset sales, as part of due diligence to relevant third parties. Other Purposes with Your
                Consent Where you expressly consent, your Personal Information might be shared with third parties,
                stipulated by additional terms to clarify specific third-party involvement in Processing your Personal
                Information.
            </p>

            <h2>Third-Party Services and Platforms</h2>
            <p>The Conqueror Services LLC Platforms might include links to third-party sites or services not controlled by
                Conqueror Services LLC, like integrated features from Google or social media (Facebook, Twitter, LinkedIn,
                etc.). Your activities on these platforms may be displayed on social media. Read the privacy policies of
                these third-party sites or platforms to understand their practices. This Policy applies solely to Personal
                Information Processed by Conqueror AI or on its behalf. How long will we keep your Personal Information?
            </p>
            <p>Conqueror Services LLC will retain your Personal Information only for the duration necessary to fulfill the
                Purposes for which it was collected or as required to serve Conqueror Services LLC's legitimate interests,
                or to comply with applicable legal, tax, or regulatory requirements. Following this period, any Personal
                Information held by Conqueror Services LLC will be securely destroyed, deleted, or rendered anonymous. For
                further information on this topic, please contact us as outlined in the "How to contact us?" section.
            </p>

            <h2>How do we protect your Personal Information?
                Ensuring Necessary and Appropriate Security Measures
            </h2>
            <p>Conqueror Services has implemented security measures to safeguard your Personal Information. The specific
                security protocols employed are contingent on the type of information collected. However, Conqueror Services
                employs physical, electronic, and procedural safeguards that adhere to applicable regulations to protect
                your Personal Information. We strongly encourage caution when using the internet, including refraining from
                sharing passwords. If you suspect an unauthorized account has been created using your details, please
                contact us as detailed in the "How to contact us?" section.
            </p>
            <h3>Increase your level of privacy:</h3>
            <p>You maintain control over the tools on your mobile devices. For instance, you can disable the GPS locator or
                Direct Push on your phone. Each Direct Push notification includes an unsubscribe link, which is explained in
                the "Why does Conqueror Services collect your Personal Information?" section.
            </p>
            <h3>CHILDREN’S PRIVACY:
            </h3>
            <p>Conqueror Services Platforms and the Service are designed and available exclusively for individuals aged 13
                years or older. Conqueror Services does not knowingly Process any Personal Information from children under
                the age of 13. If you believe Personal Information has been collected from children under the age of 13 or
                if you are a parent or legal guardian concerned that your child under 13 has provided Personal Information,
                please contact us as detailed in the "How to contact us?" section.
            </p>

            <h2>How do we use cookies?
            </h2>
            <p>A cookie is a small text file stored in a dedicated location on your computer, mobile device, tablet, or
                other devices when using your browser to visit an online service. Other tracking technologies such as web
                beacons and tracking pixels may be used for similar purposes. In this Policy, these tracking technologies
                collectively referred to as “Cookies.” Personal Information collected with Cookies by Conqueror Services or
                on its behalf receives the same level of confidentiality as any other Personal Information held by Conqueror
                Services.
            </p>

            <h2>Strictly Necessary Cookies </h2>
            <p>These Cookies are vital for the Service to function and cannot be disabled in our systems. They are necessary
                for basic Service or Conqueror Services Platforms functions, such as signing in, adding items to a cart, or
                e-billing. They maintain continuity between pages within the same session.
            </p>

            <h2>Non-essential Cookies
            </h2>
            <p>Subject to your consent, Conqueror Services and/or its third-party partners may utilize non-essential Cookies
                in connection with the Service, the Conqueror Services Platforms, and Messages, including the following:
            </p>
            <li>Functional Cookies: These enable enhanced functionality and personalization, remembering preferences and
                choices such as username, region, and language.
            </li>
            <li>Social Media Cookies: With your consent, social media Cookies like the Facebook pixel provide personalized
                offers, optimize and build audiences for advertising campaigns on social media platforms.
            </li>
            <li>Advertising Cookies: Subject to your consent, these gather information from your devices to display relevant
                advertisements and track interaction. Partners may share data with us, including statistics on ad
                performance. To manage or disable Advertising Cookies, visit <a href="">Click here</a>.
            </li>
            <li>Analytic Cookies: Used for statistical purposes, these help understand traffic patterns, measure and improve
                Service effectiveness, and track Message interactions. All information collected is aggregated and
                anonymous. To opt out of Google Analytics tracking, visit <a href="#">Click here</a>.
            </li>
            <li>Tracking Cookies: With your consent, these gather information about your usage across various websites to
                offer tailored content during Service use.
            </li>
            <p>You can refuse the use of specific Cookies by following the instructions provided below each type.
            </p>

            <h2>How to manage cookies
            </h2>
            <p>Except for strictly necessary Cookies, Conqueror Services only places Cookies on your devices upon your
                consent, and these Cookies are retained for a maximum of thirteen (13) months from their placement.
                Following this period, renewed consent is required.
            </p>
            <p>Cookie management or disabling can be performed through your browser’s Cookie settings and mobile device’s
                advertising settings. Social media Cookies (“plugins”) management can also be executed by referring to the
                policies of these networks, where applicable:
            </p>

            <p>However, refusing Cookies may limit your use of Service features, Conqueror Services Platforms, and Messages,
                while the advertisements you receive will be less tailored to your preferences. For more information on
                managing or disabling non-essential Cookies, visit <a href="#">All About Cookies</a> and <a
                    href="#">About Ads Opt-Out</a>.
            </p>

            <h2>How do we provide online advertising?
            </h2>
            <p>Conqueror Services and its third-party partners utilize Cookies, questionnaires, or mobile advertising
                identifiers to collect Personal Information for providing advertisements about goods and services. This
                could be on Conqueror Services Platforms, Establishment’s platforms, or other websites. This information is
                gathered through social media or advertising Cookies, or directly from you when participating in surveys or
                consenting to receive Messages.
            </p>
            <p>Your mobile advertising identifier (e.g., IDFA or AAID) might also be used by Conqueror Services and
                advertising partners, subject to your preferences on mobile devices, for targeting and measuring advertising
                campaign effectiveness. Conqueror Services ensures advertising is not directed at children under 13.
            </p>
            <p>For further details on advertising practices, please contact us as outlined in the "How to contact us?"
                section.
            </p>
            <p>Do Not Track
            </p>
            <p>Conqueror Services does not respond to Do Not Track (“DNT”) signals transmitted by web browsers, given the
                absence of a universally accepted standard on interpreting such signals currently.
            </p>
            <h2>Where is your Personal Information stored and transferred?
            </h2>
            <p>Your Personal Information may be held or shared by Conqueror Services with third parties in locations beyond
                your province, territory, state, or country of residence. Conqueror Services ensures the transfer of your
                Personal Information complies with legal standards, using appropriate technical, organizational,
                contractual, or lawful measures to safeguard it. For further details on security measures, please contact us
                as detailed in the "How to contact us?" section.
            </p>
            <h2>What are your rights?
            </h2>
            <p>Subject to applicable laws, you may have rights including access, rectification, withdrawal of consent,
                non-discrimination, restriction, objection, or data portability concerning your Personal Information
                Processed by Conqueror Services. To exercise these rights, please contact us as outlined in the "How to
                contact us?" section.
            </p>

            <h2>How to contact us?
            </h2>
            <p>For inquiries, comments, complaints, or to exercise your rights under applicable laws, please use the
                “Contact Us” link on the Service or Conqueror Services Platforms where available. Alternatively, contact our
                Data Protection Officer at:
            </p>
            <p>Conqueror Services LLC, City Pharmacy Bld, M02, Port Saeed, Dubai, U.A.E
            </p>
            <p>Email: <a href="mailto:info@conquerorservices.com">info@conquerorservices.com</a> </p>
            <p>Requests will be handled promptly based on applicable laws of UAE & UK. Conqueror Services LLC takes swift
                corrective action upon discovering any non-compliance with this Policy. Conqueror Services LLC shall not be
                liable for indirect, incidental, consequential, or punitive damages related to this Policy.</p>
            <p>Conqueror Services LLC is not Processing your Personal Information in a manner that is compliant with this
                Policy or with the applicable laws of U.A.E
            </p>

        </div>
    </section>
@endsection
